# Generated by Django 4.0.4 on 2022-05-22 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vending', '0002_products_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='coins',
        ),
        migrations.AddField(
            model_name='products',
            name='type',
            field=models.CharField(blank=True, choices=[('COIN', 'Coins'), ('PENNY', 'Pennies'), ('NOTE', 'Notes')], max_length=100, null=True),
        ),
    ]
