# Generated by Django 4.0.4 on 2022-05-22 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vending', '0003_remove_products_coins_products_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='type',
        ),
        migrations.AddField(
            model_name='products',
            name='coin_type',
            field=models.CharField(blank=True, choices=[('COIN', 'Coins'), ('PENNY', 'Pennies'), ('KSH', 'Kenya Shillings')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='coins',
            name='type',
            field=models.CharField(choices=[('COIN', 'Coins'), ('PENNY', 'Pennies'), ('KSH', 'Kenya Shillings')], max_length=100),
        ),
    ]
